### ISSUE TITLE
Trying to compile

### ISSUE THREAD

**Issue by S0ulfire84** [CadetEditor/CadetEngine-as#4]
I'm trying to compile a version (any stable version?) of CadetEngine/CadetEditor. In particular, Cadet2D fails because AbstractSkin2D.as defines protected function validateDisplay():Boolean, while all other skin classes are trying to implement protected function validateDisplay():void. This causes the whole thing to not compile.

**Comment by robsilv** [comment]
Hi, I'm not experiencing these compile time errors oddly... Which code editor are you using? Can you tell me which skins specifically are throwing errors and what the errors are? For release versions, check the "releases" section of each repository, i.e. https://github.com/CadetEditor/CadetEngine-as/releases
Thanks
Rob

**Comment by robsilv** [comment]
Hi @S0ulfire84, thanks for pointing out the inconsistencies with the validateDisplay() implementations. This should now be [fixed](https://github.com/CadetEditor/CadetEngine-as/commit/08d9cda9b68c217520358cbe2d3262f3372f8ee0). My hunch is that you're trying to compile the project with a stricter compiler... Are you playing with PlayScript or Haxe perhaps?

**Comment by S0ulfire84** [comment]
Hello, Robert, yes it seems it is a stricter compiler. I actually am using Flash Builder 4.6 with the Flex SDK 4.6.0 (build 23201). Nothing too fancy.

The long story is, in my Flash Builder I don't have Actionscript Library projects (maybe because it's 1.6?), which I need for creating one of the dependencies, so I tried creating Flex Library Project instead, but then I can't link against  plain AS3 projects, so I tried compiling all the libraries together with the dependencies in a single, simple swc with Cadet and Cadet2D, using the compc.exe through a FlashDevelop plugin. 

That went well with Cadet, but it failed on compilation with cadet2d. Also complained on lacking the "override" prior to overrided functions, so I'm guessing your hunch seems about right. I fixed it by hand, simply implementing the functions as booleans and that worked, but then again I don't know the internals, so I'm just fixing it using common sense, but I'm unable to evaluate the consequences.

I really like the whole idea behind Cadet, so I've been really trying hard to make it work. This is an amazing piece of work and I look forward to follow it along. Is there any roadmap of what it is lacking until version 1.0?

**Comment by robsilv** [comment]
Thanks for the feedback, glad to hear you like it! :-) No official road map yet, that's definitely something I should get around to doing... There shouldn't be any consequences I don't think (other than making it difficult for you to keep up with updates), as anything that requires a boolean to be returned was already receiving it, but it's a shame that you have to do all that in order to get it working. If you can get onto Flash Builder 4.7 and the latest AIR SDK, that should solve all your problems. Presumably you should be able to use Flash Develop too, though I haven't personally tried that yet.
I hope you can find a workflow that's easier than what you're currently having to do..! I'm going to close this issue as the validateDisplay() issue should now be solved, but let me know if you have any further issues.
